[profile.default]
[[profile.default.overrides]]
filter = 'binary(browser)'
threads-required = 'num-cpus'
retries = 2
slow-timeout = { period = "120s" }

[profile.ci]
junit.path = "junit.xml"
failure-output = "immediate-final"
fail-fast = false

[profile.ci-browser]
junit.path = "junit.xml"
failure-output = "immediate-final"
fail-fast = false
test-threads = 1
retries = 2
slow-timeout = { period = "120s" }